// File generated by Blink v0.18.1 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const stepReplication: () => void
export declare namespace DataStore {
	export namespace Player {
		export namespace Unit {
			type Default = { id: string }
		}
		type Default = { units: { id: string }[] }
	}
	export namespace Atoms {
		type PlayerMap = Map<string, { units: { id: string }[] }>
		type PayloadSync = { type: "init", data: { players: Map<string, { units: { id: string }[] }> } } | { type: "patch", data: { players: Map<string, { units: { id: string }[] }> } }
		export const sync: {
			fire: (Player: Player, Value: { type: "init", data: { players: Map<string, { units: { id: string }[] }> } } | { type: "patch", data: { players: Map<string, { units: { id: string }[] }> } }) => void
			fireAll: (Value: { type: "init", data: { players: Map<string, { units: { id: string }[] }> } } | { type: "patch", data: { players: Map<string, { units: { id: string }[] }> } }) => void
			fireExcept: (Except: Player, Value: { type: "init", data: { players: Map<string, { units: { id: string }[] }> } } | { type: "patch", data: { players: Map<string, { units: { id: string }[] }> } }) => void
			fireList: (List: Player[], Value: { type: "init", data: { players: Map<string, { units: { id: string }[] }> } } | { type: "patch", data: { players: Map<string, { units: { id: string }[] }> } }) => void
		}
		export const init: {
			on: (Listener: (Player: Player, Value: void) => void) => (() => void)
		}
	}
}
